# Generated by Django 5.2.4 on 2025-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('idambiente', models.AutoField(primary_key=True, serialize=False)),
                ('ambiente', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'ambiente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('idarea', models.AutoField(primary_key=True, serialize=False)),
                ('area', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('codigodepartamento', models.AutoField(primary_key=True, serialize=False)),
                ('departamentos', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idempresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombreempresa', models.CharField(max_length=255, unique=True)),
                ('representanteempresa', models.CharField(max_length=50)),
                ('correoempresa', models.CharField(max_length=200, unique=True)),
                ('nitempresa', models.IntegerField(unique=True)),
            ],
            options={
                'db_table': 'empresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('idhorario', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateField()),
                ('fechafin', models.DateField()),
                ('mes1', models.TextField(blank=True, null=True)),
                ('mes2', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'horario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jornada',
            fields=[
                ('idjornada', models.AutoField(primary_key=True, serialize=False)),
                ('jornada', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'jornada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Modalidad',
            fields=[
                ('idmodalidad', models.AutoField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'modalidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codigomunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('municipio', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'municipio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programaespecial',
            fields=[
                ('idespecial', models.AutoField(primary_key=True, serialize=False)),
                ('programaespecial', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'programaespecial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Programaformacion',
            fields=[
                ('codigoprograma', models.AutoField(primary_key=True, serialize=False)),
                ('nombreprograma', models.TextField(blank=True, null=True)),
                ('version', models.IntegerField()),
            ],
            options={
                'db_table': 'programaformacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idrol', models.AutoField(primary_key=True, serialize=False)),
                ('nombrerol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rol',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('idsolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('codigosolicitud', models.IntegerField()),
                ('cupo', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('subsectoreconomico', models.CharField(blank=True, max_length=100, null=True)),
                ('convenio', models.CharField(blank=True, max_length=20, null=True)),
                ('fechasolicitud', models.DateField()),
            ],
            options={
                'db_table': 'solicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoempresa',
            fields=[
                ('idtipoempresa', models.AutoField(primary_key=True, serialize=False)),
                ('tipoempresa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tipoempresa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoidentificacion',
            fields=[
                ('idtipoidentificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipoidentificacion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipoidentificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tiposolicitud',
            fields=[
                ('idtiposolicitud', models.AutoField(primary_key=True, serialize=False)),
                ('tiposolicitud', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tiposolicitud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('numeroidentificacion', models.IntegerField(unique=True)),
                ('correo', models.CharField(max_length=255, unique=True)),
                ('clave', models.CharField(max_length=255)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'usuario',
                'managed': False,
            },
        ),
    ]
