# Generated by Django 5.2.4 on 2025-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirantes',
            fields=[
                ('idaspirante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=50, unique=True)),
                ('pdf', models.TextField(blank=True, null=True)),
                ('numeroidentificacion', models.IntegerField(unique=True)),
                ('correo', models.CharField(max_length=255, unique=True)),
                ('fecha', models.DateField()),
            ],
            options={
                'db_table': 'aspirantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caracterizacion',
            fields=[
                ('idcaracterizacion', models.AutoField(primary_key=True, serialize=False)),
                ('caracterizacion', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'caracterizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipoidentificacion',
            fields=[
                ('idtipoidentificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipoidentificacion', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'tipoidentificacion',
                'managed': False,
            },
        ),
    ]
