# Generated by Django 5.2.4 on 2025-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estados',
            fields=[
                ('idestado', models.AutoField(primary_key=True, serialize=False)),
                ('estados', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'estados',
                'managed': False,
            },
        ),
    ]
