# Generated by Django 5.2.4 on 2025-08-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('idficha', models.AutoField(primary_key=True, serialize=False)),
                ('codigoficha', models.IntegerField(unique=True)),
                ('observacion', models.TextField()),
            ],
            options={
                'db_table': 'ficha',
                'managed': False,
            },
        ),
    ]
